spring.application.name=crashcourse
#spring.data.mongodb.host=localhost
#spring.data.mongodb.port=27017
spring.data.mongodb.database=journaldb
spring.data.mongodb.auto-index-creation =true
spring.data.mongodb.uri =mongodb+srv://sudha1:akVyQpiJt6594meA@cluster0.z1bl4cs.mongodb.net/?appName=Cluster0
